{% set name = "sbml2sbol" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neilswainston/SbmlToSbol/archive/{{ version }}.tar.gz
  sha256: 2c30cd73edbedc698fd6affede362752e387c3324035e7d9219b914db83f7dc2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python =3.7
    - pip
  run:
    - python =3.7
    - python-libsbml
    - synbiochem-py
    - requests

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - pytest -v tests

about:
  home: https://github.com/neilswainston/SbmlToSbol
  summary: Convert sbml to sbol format
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
